#!/usr/bin/env python
import gtk, pygtk
pygtk.require('2.0')

class tabla:
    def __init__(self):
	self.ventana = gtk.Window( gtk.WINDOW_TOPLEVEL)
	self.ventana.set_position( gtk.WIN_POS_CENTER)
	self.ventana.set_title("Ejemplo de botones de Activacion")
	self.ventana.set_size_request(400,400)
	self.ventana.set_tooltip_text("Ejemplo sobloe botones activables")

	self.boton1 = gtk.Button("Boton 1")
	self.boton1.set_border_width(15)
	self.boton1.set_tooltip_text("Este es el boton 1")
	self.boton2 = gtk.Button("Boton 2")
	self.boton2.set_border_width(15)
	self.boton2.set_tooltip_text("Este es el boton 2")
	self.boton3 = gtk.Button("Boton 3")
	self.boton3.set_border_width(15)
	self.boton3.set_tooltip_text("Este es el boton 3")

	self.caja = gtk.VBox()

	self.caja.pack_start(self.boton1)
	self.caja.pack_start(self.boton2)
	self.caja.pack_start(self.boton3)

        self.ventana.add(self.caja)
	self.ventana.show_all()
	self.ventana.connect("destroy", gtk.main_quit)

    def main(self):
	gtk.main()



if __name__ == "__main__":
    app = tabla()
    app.main()
